### PR TITLE
Script to delete annotations

### PR DESCRIPTION
**Pull request by dominikl**
I would find a script like this very helpful when testing scripts or preparing training workflows. These tasks usually create lots of file attachments, tables, ROIs, etc. Deleting them manually to get back to a clean state is a pain. With this script one can simply select a project/dataset/image/... and clean it from all annotations/rois.

If it's not generally useful, I just close the PR again...

### CODE REVIEW

**Comment by will-moore** [comment]
I can see this being useful for us (OME Training team) but I'm not sure that is enough to justify adding to the scripts we ship. But, many of those scripts are really just examples anyway, so I'm OK to add more.
For training, we have https://github.com/ome/training-scripts/blob/v0.6.0/maintenance/scripts/delete_annotations.py and https://github.com/ome/training-scripts/blob/v0.6.0/maintenance/scripts/delete_ROIs.py

**Comment by dominikl** [comment]
Is there a different repository? This whole omero-user-scripts thing seems to be rather historic, isn't it?

**Comment by jburel** [comment]
As @will-moore indicated, training-script repo is the best place for this type of scripts
Are you thinking of https://github.com/ome/omero-user-scripts?

**Comment by joshmoore** [comment]
Not sure if we already having something similar, but one option would be to split this into a discovery tool like `bin/omero annotations list` (similar to FindChildren and FindParents) and then have the ability to pipe that result to `bin/omero delete`.

cc: @mtbc

**Comment by mtbc** [comment]
This is different from just `bin/omero delete Project/Roi:1234` or whatever I guess?

**Comment by dominikl** [comment]
Whatever, I'd just like to have button (/script) in Web to simply reset any analysis results on a project. Thought that might be generally useful. Closed now.

**Pull request closed without merging**
