### PR TITLE
Include annotation_scripts in setup.py

### PR DESCRIPTION
**Pull request by pwalczysko**
Adding the annotation_scripts to setup.py as discussed

cc @jburel @sbesson @will-moore

### CODE REVIEW

**Comment by will-moore** [comment]
Oh, we have to list each package?

What about just including them all?

```
from setuptools import find_packages

packages = find_packages()
```

**Comment by pwalczysko** [comment]
@will-moore fixed in https://github.com/ome/omero-scripts/pull/204/commits/c1c4769195fa18acc984522d877b39de3f648eec

**Comment by sbesson** [comment]
Unsure whether it's related to this PR but the list of scripts does not show up in the daily merge-ci deployment

**Comment by pwalczysko** [comment]
I have reverted the commit https://github.com/ome/omero-scripts/pull/204/commits/c1c4769195fa18acc984522d877b39de3f648eec  and then ran the sequence of builds

https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-build/
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-push/
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build/

But this did not have the effect of having a scripts dropdown present on merge-ci - the dropdown is still entirely missing.
(still running omero-server build, hoping this might have some effect).

Nevertheless, although it did not help, I think that reverting the https://github.com/ome/omero-scripts/pull/204/commits/c1c4769195fa18acc984522d877b39de3f648eec was a correct decision, as I tried locally the following:

With the 
https://github.com/ome/omero-scripts/pull/204/commits/c1c4769195fa18acc984522d877b39de3f648eec 

```
$ python setup.py build
running build
$ ls
README.rst	omero		setup.py	test		test-pop-1.csv
```

Without the https://github.com/ome/omero-scripts/pull/204/commits/c1c4769195fa18acc984522d877b39de3f648eec 

```
$ python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/omero
creating build/lib/omero/analysis_scripts
copying omero/analysis_scripts/Kymograph.py -> build/lib/omero/analysis_scripts
copying omero/analysis_scripts/__init__.py -> build/lib/omero/analysis_scripts
copying omero/analysis_scripts/Kymograph_Analysis.py -> build/lib/omero/analysis_scripts
copying omero/analysis_scripts/Plot_Profile.py -> build/lib/omero/analysis_scripts
package init file 'omero/annotation_scripts/__init__.py' not found (or not a regular file)
creating build/lib/omero/annotation_scripts
copying omero/annotation_scripts/Remove_KeyVal.py -> build/lib/omero/annotation_scripts
copying omero/annotation_scripts/KeyVal_to_csv.py -> build/lib/omero/annotation_scripts
copying omero/annotation_scripts/KeyVal_from_csv.py -> build/lib/omero/annotation_scripts
creating build/lib/omero/export_scripts
copying omero/export_scripts/Batch_ROI_Export.py -> build/lib/omero/export_scripts
copying omero/export_scripts/Make_Movie.py -> build/lib/omero/export_scripts
copying omero/export_scripts/Batch_Image_Export.py -> build/lib/omero/export_scripts
copying omero/export_scripts/__init__.py -> build/lib/omero/export_scripts
creating build/lib/omero/figure_scripts
copying omero/figure_scripts/Movie_ROI_Figure.py -> build/lib/omero/figure_scripts
copying omero/figure_scripts/Split_View_Figure.py -> build/lib/omero/figure_scripts
copying omero/figure_scripts/__init__.py -> build/lib/omero/figure_scripts
copying omero/figure_scripts/Thumbnail_Figure.py -> build/lib/omero/figure_scripts
copying omero/figure_scripts/ROI_Split_Figure.py -> build/lib/omero/figure_scripts
copying omero/figure_scripts/Movie_Figure.py -> build/lib/omero/figure_scripts
creating build/lib/omero/import_scripts
copying omero/import_scripts/__init__.py -> build/lib/omero/import_scripts
copying omero/import_scripts/Populate_ROI.py -> build/lib/omero/import_scripts
copying omero/import_scripts/Populate_Metadata.py -> build/lib/omero/import_scripts
creating build/lib/omero/util_scripts
copying omero/util_scripts/__init__.py -> build/lib/omero/util_scripts
copying omero/util_scripts/Dataset_To_Plate.py -> build/lib/omero/util_scripts
copying omero/util_scripts/Combine_Images.py -> build/lib/omero/util_scripts
copying omero/util_scripts/Channel_Offsets.py -> build/lib/omero/util_scripts
copying omero/util_scripts/Images_From_ROIs.py -> build/lib/omero/util_scripts
copying omero/util_scripts/Move_Annotations.py -> build/lib/omero/util_scripts
```

i.e. the commit https://github.com/ome/omero-scripts/pull/204/commits/c1c4769195fa18acc984522d877b39de3f648eec completely prevents building anything imho.

**Comment by pwalczysko** [comment]
Edit: ah, yes, running the additional https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-server/ build was the correct idea. Now, we have the script menu on merge-ci


Screenshot 2022-11-11 at 10 33 28
Screenshot 2022-11-11 at 10 33 19

**Review by sbesson — APPROVED** [review]

**Pull request merged**
