### PR TITLE
new methods from scripts utils

### PR DESCRIPTION
**Pull request by jburel**
Update scripts to use new methods from script_utils

Check that the tests are green
see https://github.com/openmicroscopy/openmicroscopy/pull/5129

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-push#603](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/603/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-push/603/consoleText) for more details.
Possible conflicts:
  - PR #131 jburel 'Image utils'
    - omero/figure_scripts/Split_View_Figure.py

**Comment by will-moore** [comment]
From testing #5136, I see warnings from "Thumbnail figure":
```
/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/util/script_utils.py:557: DeprecationWarning: This method is deprecated as of OMERO 5.3.0. Use get_objects instead
  DeprecationWarning)
/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/util/script_utils.py:485: DeprecationWarning: This method is deprecated as of OMERO 5.3.0.         Use create_link_file_annotation instead
  DeprecationWarning)
```
which would suggest that this PR isn't merged, since warning at line 557 is from ```getObjects()``` and line 485 is ```createLinkFileAnnotation()``` which are no-longer used in this PR?

Ah - Just noticed this PR is conflicting! But I'll add the comment anyway, as a reference for testing again when it's merged.

**Comment by jburel** [comment]
@will-moore sorry I did not expect it to conflict

**Comment by will-moore** [comment]
Tests are green and Thumbnail Figure is not giving any warnings now (same for Split_View_Figure and Make_Movie).
Good to merge.

**Pull request merged**
