### PR TITLE
IDR: Remove all scripts

### PR DESCRIPTION
**Pull request by joshmoore**
This brings the `metadata` branch first up to date with the current state of the scripts repo for 5.2 and then removes all scripts so that they don't have to be disabled for every IDR deployment.

### CODE REVIEW

**Comment by joshmoore** [comment]
Travis failure is Py26 flake issue:

```
    self._parameters = utils.parameters_for(self)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/utils.py", line 297, in parameters_for
    parameters = collections.OrderedDict([
AttributeError: 'module' object has no attribute 'OrderedDict'
```

**Comment by joshmoore** [comment]
I'm going to merge this for idr 0.3.4. If it turns out this is too confusing or problematic, I'll likely force-push it away.

**Comment by joshmoore** [comment]
Note: I will set metadata54 to point at this commit as well.

cc: @jburel

**Comment by jburel** [comment]
Long term we should look into a client option "disable script" so it is easier to configure

**Comment by joshmoore** [comment]
Minimally as part of the public-user system, definitely.

**Pull request merged**
