### PR TITLE
Rtd

### PR DESCRIPTION
**Pull request by jburel**
Discussed with @sbesson and @will-moore this morning
We will keep the reference documentation in this repository
This PR replaces https://github.com/ome/omero-scripts/pull/183

* Logic in ``docs/conf.py`` to ensure that all scripts are listed in the technical documentation.

### CODE REVIEW

**Comment by jburel** [comment]
Any objections to integrate this PR?

**Comment by will-moore** [comment]
Changes look good, so 👍 

Is there a deploy of these docs anywhere yet (before this is merged)? Otherwise happy to go ahead and see how they look once merged.

**Comment by jburel** [comment]
@will-moore doc available at https://jburel-ome-scripts.readthedocs.io/en/latest/

I had to push new commits since there were a few problems with Rtd itself

**Comment by joshmoore** [comment]
This feels like a step towards being able to `pip install omero-scripts` :smile: :+1:

**Comment by jburel** [comment]
@will-moore happy with the status?

**Review by will-moore — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
