### PR TITLE
ometa with history

### PR DESCRIPTION
**Pull request by joshmoore**
This is another attempt at https://github.com/ome/omero-scripts/pull/191 but preserving the history. Steps taken:

 * used [filter-repo](https://github.com/newren/git-filter-repo) to make the move all of the user-scripts history in the target subdirectory
   - `git filter-repo --to-subdirectory-filter omero/annotation_scripts`
   - This wouldn't work if we were merging into existing directories
 * deleted the extra files towards the end
   - we could do this earlier if desired.
   - and potentially collapse all historical commits into a single one.
 * re-applied the final cleanups
 * merged into my fork with `git merge --allow-unrelated-histories --no-ff ometa/pre-rename` since applying the individual patches with `format-patch`/`am` doesn't work with merge commits sadly.

Note: this is likely something that we should make easier in the future.

cc: @will-moore @CFGrote @sbesson

### CODE REVIEW

**Comment by will-moore** [comment]
It seems there are lots of commits there that aren't related to the six files being added, e.g. https://github.com/ome/omero-scripts/pull/192/commits/f033b3577c5ac7c74adfc727104ac5f392023c8b but history is complex so it's possible.

So, once this is merged, https://github.com/ome/omero-scripts/pull/191 should merge cleanly and show changes just related to that PR?

**Comment by joshmoore** [comment]
> It seems there are lots of commits there that aren't related to the six files being added

Those are gone in #193 



> once this is merged, #191 should merge cleanly and show changes just related to that PR?

No. Only one of #191, #192 (this), or #193 should be merged. If any changes are pushed to one, the others can/should be updated.

**Comment by sbesson** [comment]
Personal preference goes towards #192 or #193 i.e. one of the propositions that preserves commit attributions.

**Comment by will-moore** [comment]
Great, #193 looks nice. #191 is broken (see my comments) but I've fixed those issues in https://github.com/mpievolbio-scicomp/omero-scripts/pull/1 which I can then open against this repo.

**Comment by CFGrote** [comment]
just merged mpievolbio-scicomp#1, anything else I can do?

**Comment by joshmoore** [comment]
@will-moore : shall we close #191 and #192 then? Just let me know if you want me to rebase https://github.com/mpievolbio-scicomp/omero-scripts/pull/1 there.

**Comment by joshmoore** [comment]
Closing in favor of #193

**Pull request closed without merging**
