### PR TITLE
Unify term

### PR DESCRIPTION
**Pull request by jburel**
Fix typos while working on https://github.com/openmicroscopy/openmicroscopy/pull/3518

### CODE REVIEW

**Comment by gusferguson** [comment]
@jburel 
- Testing https://github.com/openmicroscopy/openmicroscopy/pull/3518 - still shows Scalebar in Web and Scale bar in Insight.

This PR looks good to merge to me.

**Comment by jburel** [comment]
@gusferguson: problem in customized UI so I will fix it in the other PR.

**Comment by jburel** [comment]
Merging.

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
