### PR TITLE
Big images

### PR DESCRIPTION
**Pull request by jburel**
Use the new limit to export images as jpeg or png
To test:
- run the script on a large image. This can be done by using the export as jpeg from the right-hand panel.

### CODE REVIEW

**Comment by dominikl** [comment]
Could export an 8kx8k image without problems; code looks fine. Good to merge.

**Comment by will-moore** [comment]
You can use ```conn. getDownloadAsMaxSizeSetting()``` instead of getting config directly.

**Comment by pwalczysko** [comment]
Yes, single image of 8k x 8k download is fine. But

  - multi-select 3 images in Insight (user-4 on eel merge, 21911, 21900 and 8904) and go ``Save as jpeg``
  - observe that the action fails with

```
WARNING:omero.gateway:ApiUsageException on <class 'omero.gateway.OmeroGatewaySafeCallWrapper'> to <8e08c771-378a-4fa3-ac84-78a152353fffomero.api.RenderingEngine> getPixels((<ServiceOptsDict: {'omero.session.uuid': '3e681444-e177-4fed-ad2f-6d47efb335ee', 'omero.client.uuid': '8255542c-d46c-464e-8c58-f5f11c31ce78'}>,), {})
Traceback (most recent call last):
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4202, in __call__
    return self.f(*args, **kwargs)
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero_api_RenderingEngine_ice.py", line 475, in getPixels
    return _M_omero.api.RenderingEngine._op_getPixels.invoke(self, ((), _ctx))
ApiUsageException: exception ::omero::ApiUsageException
{
    serverStackTrace = ome.conditions.ApiUsageException: RenderingEngine not ready: Pixels object not set.
	at ome.services.RenderingBean.errorIfNullPixels(RenderingBean.java:1608)
	at ome.services.RenderingBean.getPixels(RenderingBean.java:1129)
	at sun.reflect.GeneratedMethodAccessor1285.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy113.getPixels(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1285.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy113.getPixels(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1310.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:172)
	at ome.services.throttling.Callback.run(Callback.java:56)
	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:140)
	at ome.services.blitz.impl.RenderingEngineI.getPixels_async(RenderingEngineI.java:201)
	at sun.reflect.GeneratedMethodAccessor1309.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at omero.cmd.CallContext.invoke(CallContext.java:78)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy114.getPixels_async(Unknown Source)
	at omero.api._RenderingEngineTie.getPixels_async(_RenderingEngineTie.java:186)
	at omero.api._RenderingEngineDisp.___getPixels(_RenderingEngineDisp.java:838)
	at omero.api._RenderingEngineDisp.__dispatch(_RenderingEngineDisp.java:1571)
	at IceInternal.Incoming.invoke(Incoming.java:222)
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2482)
	at Ice.ConnectionI.dispatch(ConnectionI.java:1258)
	at Ice.ConnectionI.message(ConnectionI.java:1213)
	at IceInternal.ThreadPool.run(ThreadPool.java:321)
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:693)
	at java.lang.Thread.run(Thread.java:745)

    serverExceptionClass = ome.conditions.ApiUsageException
    message = RenderingEngine not ready: Pixels object not set.
}
Traceback (most recent call last):
  File "./script", line 626, in <module>
    runScript()
  File "./script", line 611, in runScript
    fileAnnotation, message = batchImageExport(conn, scriptParams)
  File "./script", line 443, in batchImageExport
    for ch in img.getChannels():
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 7538, in getChannels
    self._conn.SERVICE_OPTS).iterateChannels())]
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4205, in __call__
    return self.handle_exception(e, *args, **kwargs)
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero/gateway/__init__.py", line 4202, in __call__
    return self.f(*args, **kwargs)
  File "/opt/hudson/workspace/OMERO-DEV-merge-deploy/src/dist/lib/python/omero_api_RenderingEngine_ice.py", line 475, in getPixels
    return _M_omero.api.RenderingEngine._op_getPixels.invoke(self, ((), _ctx))
omero.ApiUsageException: exception ::omero::ApiUsageException
{
    serverStackTrace = ome.conditions.ApiUsageException: RenderingEngine not ready: Pixels object not set.
	at ome.services.RenderingBean.errorIfNullPixels(RenderingBean.java:1608)
	at ome.services.RenderingBean.getPixels(RenderingBean.java:1129)
	at sun.reflect.GeneratedMethodAccessor1285.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy113.getPixels(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1285.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy113.getPixels(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1310.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:172)
	at ome.services.throttling.Callback.run(Callback.java:56)
	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:140)
	at ome.services.blitz.impl.RenderingEngineI.getPixels_async(RenderingEngineI.java:201)
	at sun.reflect.GeneratedMethodAccessor1309.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at omero.cmd.CallContext.invoke(CallContext.java:78)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy114.getPixels_async(Unknown Source)
	at omero.api._RenderingEngineTie.getPixels_async(_RenderingEngineTie.java:186)
	at omero.api._RenderingEngineDisp.___getPixels(_RenderingEngineDisp.java:838)
	at omero.api._RenderingEngineDisp.__dispatch(_RenderingEngineDisp.java:1571)
	at IceInternal.Incoming.invoke(Incoming.java:222)
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2482)
	at Ice.ConnectionI.dispatch(ConnectionI.java:1258)
	at Ice.ConnectionI.message(ConnectionI.java:1213)
	at IceInternal.ThreadPool.run(ThreadPool.java:321)
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:693)
	at java.lang.Thread.run(Thread.java:745)

    serverExceptionClass = ome.conditions.ApiUsageException
    message = RenderingEngine not ready: Pixels object not set.
}
```

**Comment by pwalczysko** [comment]
Note: all the three images 21911, 21900 and 8904 user-4 are exported successfully when done one-by-one.

**Comment by jburel** [comment]
@pwalczysko: the problem is not related to big images but to the multi-selection itself.

**Comment by jburel** [comment]
@pwalczysko: I found the source of the problem. I have pushed a fix in insight (the same id was passed twice.)
The script should be reviewed to avoid such issue.

**Comment by jburel** [comment]
To test the last commits:
from insight or web
 * Select the batch image export from the script menu
 * enter the same image id twice.
 * This should now pass

**Comment by pwalczysko** [comment]
Bug :  Select as user-4 on eel merge the images IDs 21911, 21900 and 8904. Then go ``Save as jpeg``. Observe Error report in Activities.

```
Traceback (most recent call last):
  File "./script", line 630, in <module>
    runScript()
  File "./script", line 615, in runScript
    fileAnnotation, message = batchImageExport(conn, scriptParams)
  File "./script", line 400, in batchImageExport
    if (pixels.getId().getValue() in ids):
AttributeError: 'long' object has no attribute 'getValue'
```

**Comment by pwalczysko** [comment]
When trying the workflow of entering the same id twice into Batch Image Export https://github.com/ome/scripts/pull/105#issuecomment-150245667 I have the same error.

**Comment by pwalczysko** [comment]
Additionaly to the tests listed under https://github.com/openmicroscopy/openmicroscopy/pull/4270#issuecomment-150565117, the test suggested by @jburel with the double-inserting of the image ID into the script form passed.

All good here. Ready to merge.

**Pull request merged**
