### PR TITLE
Remove Image.fromarray

### PR DESCRIPTION
**Pull request by jburel**
Remove usage of  ``Image.fromarray`` method
Prefer usage of io instead of StringIO

The ``numpyToImage`` method has been moved to script_utils instead of being duplicated

--depends-on https://github.com/openmicroscopy/openmicroscopy/pull/4914

### CODE REVIEW

**Comment by manics** [comment]
Is this for testing, or intended to be merged? `matplotlib` is quite a hefty module to require just for one method.

**Comment by jburel** [comment]
matplotlib is installed where omero and the scripts will be used.
Ideally the method should be moved to script_utils (omero repo), as indicated I will probably do that in another PR

**Comment by jburel** [comment]
removed labels

**Comment by will-moore** [comment]
Do we already have a requirement for matplotlib elsewhere? I couldn't see it in any of the obvious places (omeroweb, scripts, BlitzGateway). Or is it just "for free" when you install numpy?

**Comment by will-moore** [comment]
What's the difference between StringIO and io?
In BlitzGateway we often do

```
from cStringIO import StringIO

Image.open(StringIO(jpeg_data))
```

**Comment by atarkowska** [comment]
https://docs.python.org/3/library/io.html#io.StringIO `io.StringIO` handles Unicode. It reflects the preferred Python 3 library structure.

http://docs.python.org/library/stringio.html`StringIO.StringIO` handles strings. It reflects the legacy Python 2 library structure.

`cStringIO` is removed in Python 3

@will-moore why just not google?

**Comment by will-moore** [comment]
It seems that the min/max used to convert plane to image are not the global min/max for that channel but are just min/max for each plane.
I think this will mean that each plane will be normalised. This may not necessarily be a bad effect, but it might result in quite different-looking images? I'll try testing it...

**Comment by atarkowska** [comment]
@jburel Could you add review of http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/server-installation.html#python-2 to the preferred trello card please?

**Comment by atarkowska** [comment]
> Is this for testing, or intended to be merged? matplotlib is quite a hefty module to require just for one method.

@manics 

```
$ git grep -e "matplotlib"
components/tools/OmeroPy/src/omero/install/jvmcfg.py:    # See http://matplotlib.org/examples/pylab_examples/anscombe.html
components/tools/OmeroPy/src/omero/install/logs_library.py:import matplotlib.pyplot as plt
components/tools/OmeroPy/src/omero/install/logs_library.py:import matplotlib.lines as lines
components/tools/OmeroPy/src/omero/install/logs_library.py:import matplotlib.transforms as mtransforms
components/tools/OmeroPy/src/omero/install/logs_library.py:import matplotlib.text as mtext
components/tools/OmeroPy/src/omero/install/logs_library.py:# http://matplotlib.sourceforge.net/examples/api/line_with_text.html
components/tools/OmeroPy/src/omero/install/logs_library.py:            # http://matplotlib.sourceforge.net/examples/pylab_examples/broken_barh.html
components/tools/OmeroPy/src/omero/install/perf_test.py:        # import matplotlib.pyplot as plt
components/tools/OmeroPy/test/unit/test_jvmcfg.py:            # Requires matplotlib, etc
docs/install/python_deps.sh:# Various issues with matplotlib. See the following if you have problems:
docs/install/python_deps.sh:# http://superuser.com/questions/242190/how-to-install-matplotlib-on-os-x
docs/install/python_deps.sh:# http://jholewinski.org/blog/installing-matplotlib-on-os-x-10-7-with-homebrew/
docs/install/python_deps.sh:install matplotlib
```

looks like is used in multiple places

**Comment by will-moore** [comment]
Looks like matplotlib is only used for plotting log files.

**Comment by jburel** [comment]
The underline method `scriptUtil.numpyToImage` no longer uses matplotlib

**Comment by jburel** [comment]
@will-moore: if you could test the min/max change that will be great
Easy to introduce the "global" values

**Comment by will-moore** [comment]
On eel (user-4), kymographs [created with new script](http://web-dev-merge.openmicroscopy.org/webclient/?show=image-45802) appear similar (but not identical) to [with the old script](http://web-dev-merge.openmicroscopy.org/webclient/?show=image-45804).

I first tried to use latest script (with script_utils changes from https://github.com/openmicroscopy/openmicroscopy/pull/4914) but either I missed some change or I have wrong version of numpy/matplotlib.

<details>
    <summary>

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32')</summary>



```
ERROR:omero.gateway:Failed to setPlane() on rawPixelsStore while creating Image
Traceback (most recent call last):
  File "/Users/wmoore/Desktop/OMERO/openmicroscopy/dist/lib/python/omero/gateway/__init__.py", line 3410, in createImageFromNumpySeq
    plane = zctPlanes.next()
  File "./script", line 289, in planeGen
    theZ, theC, theT)
  File "./script", line 128, in getLineData
    pil = scriptUtil.numpyToImage(plane, (plane.min(), plane.max()), int32)
  File "/Users/wmoore/Desktop/OMERO/openmicroscopy/dist/lib/python/omero/util/script_utils.py", line 1260, in numpyToImage
    convArray += scaled
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

</details>

**Comment by jburel** [comment]
@will-moore This is related to the point discussed with @aleksandra-tarkowska https://github.com/openmicroscopy/openmicroscopy/pull/4914#pullrequestreview-8155232
it also occurs for 1.8 numpy

Will sort it out

**Comment by jburel** [comment]
updated description to avoid confusion

**Comment by will-moore** [comment]
So, it looks like the old `numpyToImage()` code that uses `Image.fromstring()` was actually auto-scaling from various pixel types to 8-bit PIL image. So I think the new code is not that different. No need to change it.

**Comment by jburel** [comment]
Note that now there are integration tests for the scripts
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.scriptstest.test_analysis_scripts/TestAnalysisScripts/

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/422/ are green

@will-moore ok with the changes?

**Comment by will-moore** [comment]
Yes, looks good, thanks.

**Comment by jburel** [comment]
Merging so I can fix other problems noticed

**Pull request merged**
