### PR TITLE
bom fix populate metadata

### LINKED ISSUE #179: Populate metadata and BOM
The Populate Metadata script fails if the CSV file which is fed into it has a BOM marker.
The BOM marker is easily created by following workflow

1. Open Microsoft Excel. Import (i.e. do not Open) a CSV file. Edit some bits of this file and save it again as CSV (that is how a user would inadvertently obtain a BOM merked file).

2. You can set or unset the using VIM.  (command ``set nobomb`` to unset, ``set bomb`` to set).

Suggestion: Make the Populate Metadata script robust to handle CSV files with BOM. similarly to https://github.com/ome/omero-metadata/pull/40/commits/44f69e9563f2d2c595030a94e7c51b9e21c9f1a6

cc @sbesson @manics 

```
omero_metadata.populate.MetadataError: 
Column type 'ï»¿well' unknown.
Choose from following: plate,well,image,dataset,roi,d,l,s,b
```

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #179 

To test, see ticket above for how to reproduce (create csv with `bom`).

 - Attach csv to Project/Dataset etc and run Populate_Metadata script.
 - Script should work to create bulk_annotations table.

cc @pwalczysko

### CODE REVIEW

**Comment by joshmoore** [comment]
The copy of the class is so that the next version of the scripts doesn't depend on a particular version of omero-py?

**Comment by will-moore** [comment]
Yes. Maybe I'm still thinking of "release of server-side python code is costly", and it's not such a big deal to simply use `NamedTemporaryFile` in the util class, and release `omero-py`.
But is there a way we can make the `omero-scripts` depend on the updated version of `omero-py`?

**Comment by pwalczysko** [comment]
Tested on 

1. Dataset
   - no BOM
   - with BOM
2. Plate
   - no BOM
   - with BOM

Works as expected. Ready to merge fmpov. Thank you @will-moore

**Comment by joshmoore** [comment]
> But is there a way we can make the `omero-scripts` depend on the updated version of `omero-py`?

Not directly, no. To get new scripts one will (almost certainly) need to download a new OMERO.server.zip. In those instructions, we already say to `pip install -U` but we could be more explicit about it. Perhaps the script could catch the import exception and say as much?

**Comment by will-moore** [comment]
I opened https://github.com/ome/omero-py/pull/274 so when that's released, we could revert the duplication here.
Not sure how this script would check for that change. No imports changed etc.
In due course, when we remove the duplicated code from the script, the script could handle the returned file NOT providing a temp.name and return a suitable error ("please upgrade omero-py").

**Comment by pwalczysko** [comment]
> In due course, when we remove the duplicated code from the script, the script could handle the returned file NOT providing a temp.name and return a suitable error ("please upgrade omero-py").

This is kind of a similar topic which was pointed out https://github.com/ome/omero-guide-upload/pull/13#discussion_r561761470 by @manics  - the script is dependent on omero-metadata plugin as well.

**Review by pwalczysko — APPROVED** [review]

**Comment by jburel** [comment]
> I opened [ome/omero-py#274](https://github.com/ome/omero-py/pull/274) so when that's released, we could revert the duplication here.
> Not sure how this script would check for that change. No imports changed etc.
> In due course, when we remove the duplicated code from the script, the script could handle the returned file NOT providing a temp.name and return a suitable error ("please upgrade omero-py").

A new version of omero-py has been released

**Comment by will-moore** [comment]
That last commit should detect if `omero-py 5.9.1` is not installed and tell users to upgrade.
Screenshot from running with `omero-py 5.9.0` (upgrade message) then running with `omero-py 5.9.1` (works):

Screenshot 2021-03-25 at 11 27 51

**Comment by will-moore** [comment]
Tests are failing since they appear to still be using `omero-py 5.9.0` or older?

**Comment by pwalczysko** [comment]
> Tests are failing since they appear to still be using `omero-py 5.9.0` or older?

As far as I understand it, the tests are pulling omero-server from https://hub.docker.com/layers/openmicroscopy/omero-server/latest/images/sha256-1947bf3cb3a92171455193c970b6d98cc50027d2f40363b1a94a839c126280f2?context=explore and this image was not updated since 1 month. 
Thus imho it cannot contain the omero-py 5.9.1 from 22 March and is using omero-py 5.9.0. But maybe I am wrong cc @joshmoore

**Review by sbesson — APPROVED** [review]
Thanks @will-moore, the change looks good and being able to support both CSV variants is in line with the CLI plugin.

The main downside is the handling of the `omero-py` dependency upgrade as the user will receive an error message while this will need to be fixed at the server installation level. But this issue is unrelated to this PR and will need to be solved more generically. Current best proposal would be to add the infrastructure to be able to manage `omero-scripts` like the other OMERO.server Python dependencies.

**Pull request merged**
